### ISSUE TITLE
.conf files read using default charset

### ISSUE THREAD

**Issue by binoternary** [zeldigas/spring-hocon-property-source#2]
According to [HOCON spec](https://github.com/lightbend/config/blob/master/HOCON.md#unchanged-from-json)
> files must be valid UTF-8

But in `HoconPropertySourceLoader` the `InputStreamReader` that is created uses the default charset:
```
Config config = ConfigFactory.parseReader(new InputStreamReader(resource.getInputStream()),
                ...
```

To me it seems that line should instead be
```
Config config = ConfigFactory.parseReader(new InputStreamReader(resource.getInputStream(), StandardCharsets.UTF_8),
                ...
```

**Comment by zeldigas** [comment]
@binoternary true, I'll fix that this weekend. (sorry for super late answer)

**Comment by zeldigas** [comment]
Fix pushed and published to central. Many thanks for your patience :)
